commands:
  run-scan:
    parameters:
      active-api-url:
        type: string
        default: https://electricai.nnsworkshop.com/active # change this to your active testing url
      active-test-suite-id:
        type: string
      active-severity-threshold:
        type: string # you can set to enum unless you use env variables
        default: high
        enum: ['none', 'high', 'medium', 'low', 'info']
      active-base-url:
        type: string
        default: 'http://localhost:5002'
    steps:
      - run:
          name: Noname Active-cli Docker login
          command: |
            docker login \
            --username electricai.nnsworkshop.com
            --password $ACTIVE_REGISTRY_PASSWORD jfrog.cicd.nonamesec.com/noname-docker-release
      - run:
          name: Pull Image of Noname Scanner
          command: docker pull {NONAME_ACTIVE_IMAGE_NAME:VERSION}
      - run:
          name: run Noname active Scanner
          command: |
            docker run \
            jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k https://electricai.nnsworkshop.com/active/backend/version) \
            scan \
            --api-url=https://electricai.nnsworkshop.com/active \
            --api-token=$ACTIVE_API_TOKEN \
            --test-suite-id=62f5921c-d200-4f6f-a104-29674ad30a94 \
            --severity-threshold=high \
            --base-url=http://localhost:5002

jobs:
  noname-test:
    machine: true
    steps:
      - run-scan:
          active-test-suite-id: $ACTIVE_TEST_SUITE_ID # Update with your Test Suite ID
          active-api-url: $ACTIVE_API_URL # Update with the Active Testing URI
          active-severity-threshold: $ACTIVE_SEVERITY_THRESHOLD # Update with the desired Severity threshold
          active-scan-target-base-url: $ACTIVE_BASE_URL # override the default target scan base url
