name: Active Scan

on:
  push:
    branches: [ main ]
  pull_request:
  repository_dispatch:
  workflow_dispatch:

jobs:
  active-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Standalone VAmPI Container
        # Run only the vulnerable container flavor directly on host port 5002
        run: |
          docker run -d -p 5002:5000 -e vulnerable=1 erev0s/vampi:latest
        
      - name: Test VAmPI
        run: sleep 10 && curl http://localhost:5002/ --retry 10 --retry-delay 2 

      - name: Createdb
        run: curl http://localhost:5002/createdb

      - name: Run Active Scan
        uses: nonamesec/active-scan-action@v1
        with:
          ENV_ID: "775e6c9d-dc57-4f6a-b5ba-184f1f55730b"
          ACTIVE_REGISTRY_URL: "us-central1-docker.pkg.dev/noname-artifacts/nns-docker"
          ACTIVE_REGISTRY_USER: "_json_key_base64"
          ACTIVE_REGISTRY_PASSWORD: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9uYW1lLWFydGlmYWN0cyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjU5NjdlZjBhYTdhY2EyMmNlYWFhYjVmNjIwZDIyNmRlNGQ1OTY1OGYiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFhkVjAwTi9IQkRvODhcbjloaE41OXpscjhDajFiM1hxa1c0dXlTKytaand4WmE2REZwMjFneUg4NHVab2lKVk00NGhueEtZQmNOcEk1MVBcbkR4aXZCekU2VTNQdTluRkJrR3k3U0p5UHE3NDdoUk1EUCtvU0QzQmQ3T2RLU2Q0OUFVRzB1eUIrNmJOOHpYOTBcbm1jcHB2WXFOQlBIYWZSSWRFenducG1zT2kyVVEzM2J4czBzUzlybHJ2c0NEdkxmYU1RTVhLYm9uMXdzZlVQcTJcbmdFVFpMRGx5UHNTanN2MnVHeVYxVmN5R25vNW5hVVMvT0tCMlF2VUR4d2dETlpLMlJRZ3EzZ3VldDBHQ3NWaTFcbmZmK2MxYlZLcGNGaExMWFdic3F1YlVKWFRpSEN1MmR6c3JLbno1aTQ1dEtOalE3eEpjNTlabS94YzJqeXdZeWpcbmZPZzhCbVNqQWdNQkFBRUNnZ0VBRngxeFJXUG5ITllxQ2RsQkhFS08wVmw4cWxjSkNmVXJpN2tRSlNqei9vakVcbk5ldVRYUUp6ejdZU09RWks5cWNVVFlrYVhwTG50d1RxSUl3M0VyZ0wwUDBaQi84S2dZVTBGUmVpTEV1NW1mc1pcbjRoUmVVVmUwcjI3MkZXTTlZNEFhQTRDNzZNRzd6dHpoR3FwUksrejR5MDVIZ0RCQTNEdXZEWFh1TUY1R0Zud2dcbmdLVVR2cWM2ZkZ2MytyRDZqOU85empteVZwMzZIR0NtRzBDY3Y4Q05zT1dTaitGVW81clZxTmNFN1FoZzNOb0JcblQyY29wcjZyb1BJdTEvbGJiTnpYQlZ4S0lYZEV5aFBXdTZWQjN4K1JUVjdUaVJ5c0M5eTdobXRva25aU3ovU3NcbnZoQm45ZEkyay8ydFVnejdVajI4eWU3a0hwcVhwR3FaRGFWdVlrdENJUUtCZ1FEMGZ6eDQ5dEpzNGRRTVZtNHNcbmdxaWMyck1FNkxRZ1lWejJlL3pEbkNXL2V2WGxBVW4zSForbXNTMk52REkyWDJBNTJ0SmxtUEJnYzkvSXV3RjRcbmdyWWF0RUkxdWR0eDQyZzI3WXlWRnppODFacGozc0JjZWdJOHVDc1JuZGY1V0RuUU5yQXVMYy9FVHdGSVVHNFlcbjhMSlRHS3BqcUVZT2RIbXJYODhONWNvejB3S0JnUURobUdIb09JR2MrOTA0UDhTdnBtTGZzNmNBOStnV2g5SHJcblFUa3hETVZTamNJam9kVGozaW9iMmdQWDkycEZ0V3pvNkJpWitMRDZjNmZtc0xyWGhyNzA5TjR4Z3NxZHVrZDJcbngvclQxNzBSbm5BbTdzOE5JcE9KSm5mU3BTOVVmNlNPTjlXTXptUk9xKzkzK0lOZDN6VGErM0t0OXlmUFovUGRcblVydzcyblFaOFFLQmdDM1d1UUM0emNUS0poWldFZnZZVjBKcElrMFdUOGNPV2Y2QVNtaG1HeEdtUFBtOVh4K3NcbmR5VXFiSzc1RExUeTlyaUNGUllsTVZQMEJZMjl1YzNkTzhVUDdLWGovWWVCcWlVNkxqUTVrVktkL1g4aDRSQzFcbmN6dnREMjRUR00zUHc2OE13Y1UybzVCYmU1TVNPVUlGeG5rYjA3NHhhMGtFZjFjbzlFblh2aXd2QW9HQkFJc2Rcbml4TEc5YmEyNGw1emhIakU1Q2dMQXl0bnRPbGY3Q1ZrM1QzUUlFYWVRRi8weGZHVzZPU3Y5cnJSU2VtZXpZQjZcbnorRHpLVC9vM2xzMkZLSWY1OVhxd3JKSmMyVDhvR0V4UlE0cDlkL05rbCtQMklMREZiUDMwdUJGR1FERWpkZGRcbnV3VFBxYStSKzJSQ0RkQnZlb3Fua0xxU3RTd0RjTERFK21yMmRhNGhBb0dBQmNLbElaK0dMZnB3ZWlVK0JQZDFcbmhwUlU4OXQ3d3R4Yk11c0ljV0JzaGoyNDErRjhlNnFhcHB2UlkvYXZ1U3VBd1FTb0EvRUIrRmZ1RnR4bFpPR1BcbjNtZUdZWlE4dWplc01ZYkNZQmlzemJhbTR0VmVtWTJheEpuQ2YvUVFnMndSQ3JzOTRQKzJWc0F6TGFNRDIrc0JcbkJWeHhVMlp0R3RCMGV5YzdtdEV6L2ZZPVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImFjdGl2ZS1kZW1vQG5vbmFtZS1hcnRpZmFjdHMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA0NjEzMjAzNjE5OTI2MTcxNDIwIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9hY3RpdmUtZGVtbyU0MG5vbmFtZS1hcnRpZmFjdHMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"
          ACTIVE_API_URL: "https://active-demo.nonamesec.com/active"
          CORE_CLI_CLIENT_ID: "9cc6ef9433355655678b4e3adc8b4ae165f7bed5a4664f66cc3a381acb6fcd3b"
          CORE_CLI_CLIENT_SECRET: "ba9fca69c8a1fbe47195671f1dfcce39605e0bd5dcdca31973a1a1b857c84ff73b3a61b351687d8a19a55f8336a8b9bce17b30cb32d8bd70ebf4b0d3c05e0ead"
          ACTIVE_BACKEND_URI: "https://active-demo.nonamesec.com/active/backend"
          TEST_GROUP_ID: "892b51de-67cf-4328-beea-3ade61bcdeb2"
          BRANCH_NAME: "${{ github.ref_name }}"
          VERBOSE: "true"
          ANALYZE: "true"
          USE_ZAP: "false"

  deploy:
    needs: active-scan 
    runs-on: ubuntu-latest 
    steps:
      - name: echo
        run: echo Security scan passed, deploying to production
