name: Active Scan

on:
  push:
    branches: [ main ]
  pull_request:
  repository_dispatch:
  workflow_dispatch:

jobs:
  active-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Standalone VAmPI Container
        # Run only the vulnerable container flavor directly on host port 5002
        run: |
          docker run -d -p 5002:5000 -e vulnerable=1 erev0s/vampi:latest
        
      - name: Test VAmPI
        run: sleep 10 && curl http://localhost:5002/ --retry 10 --retry-delay 2 

      - name: Createdb
        run: curl http://localhost:5002/createdb

      - name: Run Active Scan
        uses: nonamesec/active-scan-action@v1
        with:
          ENV_ID: "89e0682a-efc0-43f8-9c98-cbf2852049d5"
          ACTIVE_REGISTRY_URL: "us-central1-docker.pkg.dev/noname-artifacts/nns-docker"
          ACTIVE_REGISTRY_USER: "_json_key_base64"
          ACTIVE_REGISTRY_PASSWORD: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAibm9uYW1lLWFydGlmYWN0cyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjY5ZjFkZDRkZDNhMWU0YzZlODY0NmM1NTM2ZGE1NDQ2NzIwNzllZjIiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRENoVVRYbERzeEsxMEJcbkxnWFA5elZBeVZhQWlaQVZUZVdCckpuOWlHT3FhRTdHK3hyU0JMRXdQQzFNU1EwcDRvbFlLYTk3Qy9KcVZEMWFcblNyZks0VG01UG1aL1drSWZBY3hqRGZIZHRYajk4MjgyWGYvMndzdU9OaWlmVGRuRGJXZmVubjAzVEZYMzFhNzZcbnJ5Zks1OTRBeWFDOGFJZG9VMzJqa3FYWkgycXBENjlqV28zS1hoaWxGQWhVbGhSSlBDejZibzIzTkF5SFFPM1dcbnh5ZlNFY3pscGdmVS96N3Bnd1VqTXltdEpDUEFLY29mdWVZb2NiQzF3WkZhOUR2ZGlyN1dkSU8xaWRmWlJERUZcbmNFdW9CMFdGTVVZRVFtSmhkRnRhNDZ2S1pORGhzVHVKbTBzN1BTa1k1VTNaS3lJekJsZGNLVDdyVzl0RGl2aGVcbkcrOCtNYUdmQWdNQkFBRUNnZ0VBVk1GenR3a0g1NHN3NllBdm1TZHFKVEgxQm1tcUJaWmMzMjBnNWJibFVrMURcbnNmQ2NoWkQwMFlNTzY3UFMwQUs4ZkZVaGVGaEN4bkN4RU9RSWhCWXhyQlRUM1Q2ckc4NlJTMEc2dHJOSkprSEpcbkhlUEVVVFVjTTNsR3B1N3BhUDBGS3B0ZEROaXVocCt0TDk1YzFNekZ6d3NMaGJ4Mzc0MmRhMFhORExkakpva0RcbjhyTlpNSXcvczhKd3NmdVZuOEZJanZ4Y0pWMXB0WFlQVy90USsrUzdlWUZ0YzhkZXI5dXh0Yk5NU21GL2tDeGJcbmV3M1I1SWxZM1VYRldPN1JGRjRPNVUvUDRLNE11MFJaRXlUK1huMmVBTmVyajhLRXBtVUhrdDhwYmlEU0VpcTdcbnpXdkNOYkxjY1NHaFB6T294WDhLNEt4bTdHYnhtZ1ZnWlN5Uk51Y3dWUUtCZ1FEbjlMVVVZbDFnN3dRRFBtNTBcbjA1YndlTldRL20rbXV1aHMzM2p6UGZBeWQ5QlJwUXMySkxyaEhzK00vV2lCQmljNDV4cTlEbHphd0NqWkFvM1Vcbi92Q0xrdVh2UmQrTzFOd1l3aHRwRHNzdUx6dkF2eEpxcDl6c3lDeDMxNHpPaEU0ZmREQmxNZkpYRDI4UkgvbitcbllkaWtGeEIyN2VId2FYaTdKNDI2OFV6d0hRS0JnUURXcnlrTHFGNFlSTVFocmx3cFN4a3crWThZL2FoK1VaRlNcbk1OZGRuVEZrUzljbGZZcmNsM09MM2w1VTdkT1FVTUN3NnUvMEhycERaeW40VEw1NVR4TnpFYWJFQkpzWElPNjZcblliSUc0VXVtWS84bmdxMTE1UWVpTmw2YnJPNjNQaUhuTHk2enNaaVU0d1BMclNGaE12VDVzbTV3M3J0aVhuaVVcbmJic2NhSzVqNndLQmdRQ2lCNXFHaHIvYitwcSsrVm1IV2xiUjNGYXpWa2tBR3doSkpVSUVDSHhGaE5TTWM5SUZcbkhGcys3cHJsVGc4Mk1lb3NJYVBYOUxTQVNrTStkRDVIVDE4UTRLaW1JQlV1WFJyeVlJVnRPZHhNZ3NvbXRsSlRcbkZyZUkzN3ZRYTAzODVRYjlpZGhVbURORkJZNzhVMjM2ZUxjd3lMdkRtQ0NBSSswbUwxY2VBM2xQTVFLQmdRQ0RcblEzQWVUNkRReCtNQUVRTUt3SDh6b2JNci9aUnpQOTVSMmNrazFRTXBKdkh5VzFOM1V5YjBBMCs4TC9vbWlDbDVcblF2emFUNXRsc1FOSmJXc2M4d3VhVk5XWmpwTmhUZUtKbFVocnluOGR5cEJ0RVFxTVJqQW5yNFNqUE5ac3RoRzJcbnIvT25MVlIwM0dVcXVMM3JGMlFQOUZod3JNNzM4M2xZajh0VE1ISklad0tCZ1FDdkJ1TEs4L2ZxK1hRQ3pjVGRcbkwxMDVIR0JhMGRtRmxpc25UQlUydVBHMXhMZDhKcFdXc2ZsL0hHZjg5Vm1ZSTU3WHZYaEpBUFU0ODhwZnQzektcbjg0SXo3ankzQVZrc2srNForZmtlbHhGM2pKYXJRbE9MT0Z4TVFCbWhTb1dYZEg0dmhHek1rdHl1MHh0U0tJSHVcbnlFYzZuSkorQ2xGa25rV3pwbDJpWjRYNHV3PT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJtcy1waGFzZTMtdGVzdEBub25hbWUtYXJ0aWZhY3RzLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjExMzU4NDA3MTU0OTczNzUwNzUzMyIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvbXMtcGhhc2UzLXRlc3QlNDBub25hbWUtYXJ0aWZhY3RzLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg=="
          ACTIVE_API_URL: "https://ms-phase3-test.nonamesec.com/active"
          ACTIVE_API_TOKEN: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlLZXkiOiI5N2IzOGU5Zi00YjZiLTQ3ZjEtYjFhNy1lZGMwZWRkOThjOWQiLCJpZCI6IjE1ZTYzNDhmLTdhMDktNDE5ZC04MGJiLWVhN2YyNGQ5YTFkMyIsImlhdCI6MTc4MDI1MTI3MywiZXhwIjoxNzk1ODAzMjczLCJhdWQiOlsibm9uYW1lLW1hbmFnZW1lbnQtYXBpIl0sImlzcyI6Im5vYXV0aCJ9.htsP_SuQZdv8-G_P-pVY-NcTdMmzDbE4wFn1QoNEJnitk5fgxAu1TveLL6tL7UBcB84eqqoVlwmXz-nrP0Y_HarLmnCNFhXamRDOedW19KQ-UWtUGx16L2NMuYsSuJswklzjfPeMOGK2A2qm7pP75QdcRujwtVQIKx4RDLsnJAv9qQwZVe2tK_7gdoAd71NrylNJJvjzspKhhRD1xOIgNM3G_C5vMygWF0ZIRx6eIiUB8hwZ3qVV1jCJ0ZtUlJljv7ARfKhuRxpY0pl164mjbzbmincYgXPzNuJ7pFbxcBEqb8kJcUxp4zDqGj_MJF68FE6CpG4IFlO0mDAvVyQ0AQ"
          ACTIVE_BACKEND_URI: "https://ms-phase3-test.nonamesec.com/active/backend"
          TEST_GROUP_ID: "892b51de-67cf-4328-beea-3ade61bcdeb2"
          BRANCH_NAME: "${{ github.ref_name }}"
          VERBOSE: "true"
          ANALYZE: "true"

  deploy:
    needs: active-scan 
    runs-on: ubuntu-latest 
    steps:
      - name: echo
        run: echo Security scan passed, deploying to production
